/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek_basda_praktikum;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class addUserForm extends javax.swing.JFrame {

    private DefaultTableModel tabMode;
    private ResultSet hasil;

    CRUDuser cr = new CRUDuser();

    public addUserForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        x_close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_add_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_add_password = new javax.swing.JPasswordField();
        btn_add_clos = new javax.swing.JButton();
        btn_add_add = new javax.swing.JButton();
        txt_add_nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_add_telepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combox_add_creditial = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        radio_add_genderL = new javax.swing.JRadioButton();
        radio_add_genderP = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_add_alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        x_close.setBackground(new java.awt.Color(255, 255, 255));
        x_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        x_close.setForeground(new java.awt.Color(255, 255, 255));
        x_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x_close.setText("X");
        x_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x_closeMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add User Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(x_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(x_close, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");

        txt_add_username.setBackground(new java.awt.Color(248, 148, 6));
        txt_add_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_add_username.setForeground(new java.awt.Color(44, 62, 80));
        txt_add_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_add_usernameActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");

        txt_add_password.setBackground(new java.awt.Color(248, 148, 6));
        txt_add_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_add_password.setForeground(new java.awt.Color(44, 62, 80));
        txt_add_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_add_passwordActionPerformed(evt);
            }
        });

        btn_add_clos.setBackground(new java.awt.Color(242, 38, 19));
        btn_add_clos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_add_clos.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_clos.setText("Cancel");
        btn_add_clos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add_clos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_closActionPerformed(evt);
            }
        });

        btn_add_add.setBackground(new java.awt.Color(31, 58, 147));
        btn_add_add.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_add_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_add.setText("add");
        btn_add_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_addActionPerformed(evt);
            }
        });

        txt_add_nama.setBackground(new java.awt.Color(248, 148, 6));
        txt_add_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_add_nama.setForeground(new java.awt.Color(44, 62, 80));
        txt_add_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_add_namaActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama:");

        txt_add_telepon.setBackground(new java.awt.Color(248, 148, 6));
        txt_add_telepon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_add_telepon.setForeground(new java.awt.Color(44, 62, 80));
        txt_add_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_add_teleponActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telepon:");

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Creditial:");

        combox_add_creditial.setBackground(new java.awt.Color(248, 148, 6));
        combox_add_creditial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combox_add_creditial.setForeground(new java.awt.Color(44, 62, 80));
        combox_add_creditial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir" }));
        combox_add_creditial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combox_add_creditial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_add_creditialActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender:");

        radio_add_genderL.setBackground(new java.awt.Color(248, 148, 6));
        buttonGroup1.add(radio_add_genderL);
        radio_add_genderL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio_add_genderL.setForeground(new java.awt.Color(255, 255, 255));
        radio_add_genderL.setText("L");
        radio_add_genderL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_add_genderL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_add_genderLActionPerformed(evt);
            }
        });

        radio_add_genderP.setBackground(new java.awt.Color(248, 148, 6));
        buttonGroup1.add(radio_add_genderP);
        radio_add_genderP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radio_add_genderP.setForeground(new java.awt.Color(255, 255, 255));
        radio_add_genderP.setText("P");
        radio_add_genderP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alamat:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_add_alamat.setBackground(new java.awt.Color(248, 148, 6));
        txt_add_alamat.setColumns(20);
        txt_add_alamat.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_add_alamat.setForeground(new java.awt.Color(44, 62, 80));
        txt_add_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_add_alamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_add_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_add_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_add_username, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_add_clos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_add_add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_add_password)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radio_add_genderL)
                                .addGap(18, 18, 18)
                                .addComponent(radio_add_genderP))
                            .addComponent(combox_add_creditial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combox_add_creditial, txt_add_nama, txt_add_password, txt_add_telepon, txt_add_username});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_add_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_add_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_add_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_add_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_add_creditial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_add_genderL)
                    .addComponent(radio_add_genderP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_clos)
                    .addComponent(btn_add_add))
                .addGap(21, 21, 21))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combox_add_creditial, txt_add_nama, txt_add_password, txt_add_telepon, txt_add_username});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x_closeMouseClicked
        try {
            this.dispose();
            main form = new main();
            form.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(addUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_x_closeMouseClicked

    private void txt_add_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_add_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_add_usernameActionPerformed

    private void txt_add_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_add_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_add_passwordActionPerformed

    private void btn_add_closActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_closActionPerformed
        try {
            this.dispose();
            main form = new main();
            form.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(addUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_closActionPerformed

    private void btn_add_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_addActionPerformed
        String gender = "";
        if (txt_add_username.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_username.requestFocus();
        } else if (txt_add_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_nama.requestFocus();
        } else if (txt_add_password.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_password.requestFocus();
        } else if (txt_add_alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_alamat.requestFocus();
        } else if (txt_add_telepon.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_telepon.requestFocus();
        } else if (radio_add_genderL.isSelected()) {
            gender = "L";
        } else if (radio_add_genderP.isSelected()) {
            gender = "P";
        } else {
            cr.setCredential(combox_add_creditial.getSelectedItem().toString());
//            String username="",nama="",password="",alamat="",telepon="";
            cr.setUsername(txt_add_username.getText());
            cr.setNama(txt_add_nama.getText());
            cr.setPassword(txt_add_password.getText());
            cr.setAlamat(txt_add_alamat.getText());
            cr.setTelepon(txt_add_telepon.getText());
            cr.setGender(gender);
            try {

                cr.save(cr.getUsername(), cr.getNama(), cr.getPassword(), cr.getTelepon(), cr.getAlamat(), cr.getGender(), cr.getCredential());

            } catch (Exception e) {
            }
        }
        reset();
    }//GEN-LAST:event_btn_add_addActionPerformed

    private void txt_add_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_add_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_add_namaActionPerformed

    private void txt_add_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_add_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_add_teleponActionPerformed

    private void radio_add_genderLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_add_genderLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_add_genderLActionPerformed

    private void combox_add_creditialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_add_creditialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_add_creditialActionPerformed
    private void textfield() {
//        Object[] baris = {"username","nama","password","alamat","telepon"};
        String gender = "";
        if (txt_add_username.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_username.requestFocus();
        } else if (txt_add_nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_nama.requestFocus();
        } else if (txt_add_password.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_password.requestFocus();
        } else if (txt_add_alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_alamat.requestFocus();
        } else if (txt_add_telepon.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data belum di isi");
            txt_add_telepon.requestFocus();
        } else if (radio_add_genderL.isSelected()) {
            gender = "L";
        } else if (radio_add_genderP.isSelected()) {
            gender = "P";
        } else {
//            String username="",nama="",password="",alamat="",telepon="";
            cr.setCredential(combox_add_creditial.getSelectedItem().toString());
            try {
                cr.setUsername(txt_add_username.getText());
                cr.setNama(txt_add_nama.getText());
                cr.setPassword(txt_add_password.getText());
                cr.setAlamat(txt_add_alamat.getText());
                cr.setTelepon(txt_add_telepon.getText());
                cr.setGender(gender);
                cr.save(cr.getUsername(), cr.getNama(), cr.getPassword(), cr.getTelepon(), cr.getAlamat(), cr.getGender(), cr.getCredential());

            } catch (Exception e) {
            }
        }
    }

    public void credential() {
        try {
            cr.setCredential(combox_add_creditial.getSelectedItem().toString());
            System.out.println(combox_add_creditial.getSelectedItem().toString());
        } catch (Exception e) {
        }
    }

    public void reset() {
        txt_add_username.setText("");
        txt_add_nama.setText("");
        txt_add_password.setText("");
        txt_add_telepon.setText("");
        txt_add_password.setText("");
        radio_add_genderL.setSelected(false);
        radio_add_genderP.setSelected(false);
        combox_add_creditial.setSelectedItem(null);
        txt_add_alamat.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_add;
    private javax.swing.JButton btn_add_clos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combox_add_creditial;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio_add_genderL;
    private javax.swing.JRadioButton radio_add_genderP;
    private javax.swing.JTextArea txt_add_alamat;
    private javax.swing.JTextField txt_add_nama;
    private javax.swing.JPasswordField txt_add_password;
    private javax.swing.JTextField txt_add_telepon;
    private javax.swing.JTextField txt_add_username;
    private javax.swing.JLabel x_close;
    // End of variables declaration//GEN-END:variables
}
